version: '3'
services:
  docker-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-challenge
  scrapper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: scraper-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
